-- ============================================================================
-- DEV/DEMO SEED — Dwarka, New Delhi. GENERATED by db/gen_dwarka_seed.py.
-- Cameras at REAL OpenStreetMap traffic-signal junctions; links OSRM-routed.
-- Re-runnable; TRUNCATEs the network — STOP the pipeline workers first.
-- ============================================================================
BEGIN;
TRUNCATE cameras, roads, plates, camera_links, sightings, blacklist_entries,
         alerts, camera_metrics_5m, traffic_metrics_5m RESTART IDENTITY CASCADE;

INSERT INTO roads (road_code, name) VALUES ('DWK-CORR-1', 'Dwarka Signal Corridor');

INSERT INTO cameras (camera_code, display_name, location, heading_degrees, status) VALUES
  ('CAM-01', 'Shivaji Marg signal', ST_SetSRID(ST_MakePoint(77.024537, 28.619977), 4326), 180, 'active'),
  ('CAM-02', 'Azad Hind Fauj Marg signal', ST_SetSRID(ST_MakePoint(77.035697, 28.60629), 4326), 180, 'active'),
  ('CAM-03', 'Mall Road signal', ST_SetSRID(ST_MakePoint(77.039469, 28.603704), 4326), 180, 'active'),
  ('CAM-04', 'Road No. 201 signal', ST_SetSRID(ST_MakePoint(77.067438, 28.596376), 4326), 180, 'active'),
  ('CAM-05', 'Rd. No. 224 signal', ST_SetSRID(ST_MakePoint(77.069232, 28.590778), 4326), 180, 'active'),
  ('CAM-06', 'Dwarka Junction 6', ST_SetSRID(ST_MakePoint(77.061651, 28.581808), 4326), 180, 'active'),
  ('CAM-07', 'Dwarka Junction 7', ST_SetSRID(ST_MakePoint(77.069534, 28.57658), 4326), 180, 'active'),
  ('CAM-08', 'Dwarka Junction 8', ST_SetSRID(ST_MakePoint(77.062501, 28.563226), 4326), 180, 'active');

INSERT INTO camera_links (from_camera_id, to_camera_id, road_id, direction_label, path, distance_meters, free_flow_time_seconds, speed_limit_kph)
SELECT f.camera_id, t.camera_id, r.road_id, 'FWD',
       ST_SetSRID(ST_GeomFromGeoJSON('{"coordinates": [[77.024522, 28.619938], [77.02431, 28.620004], [77.024334, 28.620088], [77.025347, 28.619766], [77.026547, 28.61938], [77.027079, 28.619346], [77.027819, 28.619278], [77.028079, 28.619257], [77.028642, 28.619212], [77.028816, 28.619191], [77.029003, 28.619174], [77.029398, 28.619151], [77.029434, 28.619147], [77.02963, 28.619145], [77.029789, 28.619143], [77.02997, 28.619138], [77.030159, 28.619134], [77.031008, 28.619111], [77.031073, 28.619114], [77.031111, 28.619115], [77.031418, 28.619129], [77.031576, 28.619145], [77.031625, 28.618953], [77.031735, 28.618496], [77.03184, 28.618065], [77.031923, 28.617761], [77.032046, 28.617317], [77.032187, 28.616846], [77.032341, 28.61637], [77.03269, 28.615309], [77.033435, 28.613117], [77.033608, 28.61257], [77.033711, 28.612247], [77.034986, 28.608425], [77.034992, 28.608409], [77.035144, 28.607946], [77.035676, 28.606326], [77.035697, 28.60629]], "type": "LineString"}'), 4326), 2236, 158, 50
FROM cameras f, cameras t, roads r
WHERE f.camera_code='CAM-01' AND t.camera_code='CAM-02' AND r.road_code='DWK-CORR-1';
INSERT INTO camera_links (from_camera_id, to_camera_id, road_id, direction_label, path, distance_meters, free_flow_time_seconds, speed_limit_kph)
SELECT f.camera_id, t.camera_id, r.road_id, 'REV',
       ST_SetSRID(ST_GeomFromGeoJSON('{"coordinates": [[77.035697, 28.60629], [77.035697, 28.60629], [77.035726, 28.60624], [77.035553, 28.606176], [77.035526, 28.60623], [77.035507, 28.60627], [77.035057, 28.607626], [77.035024, 28.607726], [77.034521, 28.60925], [77.034247, 28.610092], [77.034079, 28.610621], [77.033897, 28.611163], [77.033841, 28.611335], [77.033452, 28.612538], [77.033163, 28.613415], [77.033061, 28.613722], [77.032902, 28.614206], [77.032763, 28.614622], [77.032594, 28.615125], [77.032361, 28.61583], [77.032298, 28.616026], [77.032087, 28.616689], [77.031782, 28.617711], [77.03159, 28.618393], [77.031432, 28.618562], [77.031185, 28.618925], [77.03067, 28.618907], [77.030417, 28.618909], [77.030197, 28.61891], [77.029698, 28.618961], [77.029464, 28.618985], [77.029302, 28.619003], [77.029168, 28.619018], [77.029099, 28.619023], [77.028924, 28.619034], [77.028734, 28.619047], [77.028553, 28.619059], [77.028359, 28.619072], [77.028158, 28.619085], [77.027965, 28.619098], [77.027799, 28.619109], [77.027628, 28.61912], [77.027593, 28.619124], [77.027391, 28.619147], [77.027062, 28.619184], [77.026679, 28.619223], [77.026641, 28.619229], [77.026496, 28.619227], [77.026439, 28.619228], [77.026274, 28.619365], [77.025919, 28.619498], [77.025374, 28.619675], [77.025201, 28.619728], [77.024522, 28.619938]], "type": "LineString"}'), 4326), 2175, 153, 50
FROM cameras f, cameras t, roads r
WHERE f.camera_code='CAM-02' AND t.camera_code='CAM-01' AND r.road_code='DWK-CORR-1';
INSERT INTO camera_links (from_camera_id, to_camera_id, road_id, direction_label, path, distance_meters, free_flow_time_seconds, speed_limit_kph)
SELECT f.camera_id, t.camera_id, r.road_id, 'FWD',
       ST_SetSRID(ST_GeomFromGeoJSON('{"coordinates": [[77.035697, 28.60629], [77.035697, 28.60629], [77.035726, 28.60624], [77.038302, 28.604483], [77.039469, 28.603704]], "type": "LineString"}'), 4326), 468, 33, 50
FROM cameras f, cameras t, roads r
WHERE f.camera_code='CAM-02' AND t.camera_code='CAM-03' AND r.road_code='DWK-CORR-1';
INSERT INTO camera_links (from_camera_id, to_camera_id, road_id, direction_label, path, distance_meters, free_flow_time_seconds, speed_limit_kph)
SELECT f.camera_id, t.camera_id, r.road_id, 'REV',
       ST_SetSRID(ST_GeomFromGeoJSON('{"coordinates": [[77.039469, 28.603704], [77.039469, 28.603704], [77.039557, 28.603646], [77.039465, 28.603534], [77.039396, 28.603581], [77.038204, 28.604376], [77.037804, 28.604642], [77.036868, 28.60528], [77.035553, 28.606176], [77.035526, 28.60623], [77.035507, 28.60627], [77.035592, 28.606307], [77.035676, 28.606326], [77.035697, 28.60629]], "type": "LineString"}'), 4326), 541, 53, 50
FROM cameras f, cameras t, roads r
WHERE f.camera_code='CAM-03' AND t.camera_code='CAM-02' AND r.road_code='DWK-CORR-1';
INSERT INTO camera_links (from_camera_id, to_camera_id, road_id, direction_label, path, distance_meters, free_flow_time_seconds, speed_limit_kph)
SELECT f.camera_id, t.camera_id, r.road_id, 'FWD',
       ST_SetSRID(ST_GeomFromGeoJSON('{"coordinates": [[77.039469, 28.603704], [77.039469, 28.603704], [77.039557, 28.603646], [77.041631, 28.602218], [77.042203, 28.601843], [77.042635, 28.602341], [77.043092, 28.602748], [77.043664, 28.60323], [77.044355, 28.603666], [77.044799, 28.603923], [77.045006, 28.604043], [77.045778, 28.604404], [77.046498, 28.60469], [77.046921, 28.60483], [77.047401, 28.604956], [77.048206, 28.605121], [77.049327, 28.605292], [77.050229, 28.605312], [77.050653, 28.605304], [77.051511, 28.605211], [77.051902, 28.605143], [77.052371, 28.605045], [77.052862, 28.604921], [77.053378, 28.604762], [77.053901, 28.604571], [77.054156, 28.604455], [77.054248, 28.604412], [77.054789, 28.60415], [77.055268, 28.603883], [77.0558, 28.603552], [77.055837, 28.603528], [77.055887, 28.603495], [77.055928, 28.603469], [77.056458, 28.603144], [77.05656, 28.603074], [77.058287, 28.601899], [77.058366, 28.601846], [77.059763, 28.600899], [77.060172, 28.600615], [77.061059, 28.600041], [77.061085, 28.600024], [77.06111, 28.600008], [77.061695, 28.599643], [77.061882, 28.599526], [77.061996, 28.599441], [77.062079, 28.599392], [77.062327, 28.599245], [77.062977, 28.598814], [77.063241, 28.598638], [77.063551, 28.598426], [77.063647, 28.598361], [77.064146, 28.598006], [77.064224, 28.597951], [77.064492, 28.597765], [77.064633, 28.597667], [77.064908, 28.597475], [77.065047, 28.597379], [77.065276, 28.597243], [77.06559, 28.597118], [77.06731, 28.596518], [77.067344, 28.596507], [77.067419, 28.596481], [77.067463, 28.596466], [77.067399, 28.596391], [77.067362, 28.596348], [77.06728, 28.596252], [77.067911, 28.596016], [77.068334, 28.595859], [77.06838, 28.595841], [77.068998, 28.595631], [77.069188, 28.595572], [77.069233, 28.595647], [77.069272, 28.595711], [77.067984, 28.59617], [77.067438, 28.596376]], "type": "LineString"}'), 4326), 3666, 291, 50
FROM cameras f, cameras t, roads r
WHERE f.camera_code='CAM-03' AND t.camera_code='CAM-04' AND r.road_code='DWK-CORR-1';
INSERT INTO camera_links (from_camera_id, to_camera_id, road_id, direction_label, path, distance_meters, free_flow_time_seconds, speed_limit_kph)
SELECT f.camera_id, t.camera_id, r.road_id, 'REV',
       ST_SetSRID(ST_GeomFromGeoJSON('{"coordinates": [[77.067438, 28.596376], [77.067438, 28.596376], [77.067399, 28.596391], [77.067354, 28.596408], [77.067285, 28.596431], [77.065545, 28.597026], [77.065228, 28.597159], [77.065004, 28.597289], [77.064393, 28.597698], [77.06415, 28.597881], [77.063567, 28.598267], [77.063483, 28.598335], [77.063161, 28.598558], [77.062236, 28.599175], [77.061899, 28.599388], [77.061036, 28.599928], [77.059694, 28.600819], [77.058224, 28.601824], [77.056392, 28.603056], [77.055847, 28.60338], [77.055721, 28.603458], [77.055304, 28.603712], [77.055064, 28.603862], [77.054313, 28.604264], [77.053829, 28.60447], [77.053389, 28.604633], [77.052825, 28.604814], [77.052198, 28.604972], [77.051623, 28.605079], [77.051121, 28.605141], [77.050212, 28.605212], [77.049332, 28.605187], [77.048224, 28.605026], [77.047429, 28.60486], [77.046538, 28.604595], [77.045985, 28.604382], [77.045812, 28.604319], [77.045058, 28.603952], [77.044401, 28.603581], [77.043749, 28.603145], [77.043195, 28.602688], [77.042687, 28.602211], [77.042322, 28.601766], [77.042265, 28.601683], [77.042158, 28.601757], [77.041684, 28.60207], [77.039465, 28.603534], [77.039396, 28.603581], [77.038204, 28.604376], [77.037804, 28.604642], [77.036868, 28.60528], [77.035553, 28.606176], [77.035526, 28.60623], [77.035507, 28.60627], [77.035592, 28.606307], [77.035676, 28.606326], [77.035697, 28.60629], [77.035726, 28.60624], [77.038302, 28.604483], [77.039469, 28.603704]], "type": "LineString"}'), 4326), 4207, 296, 50
FROM cameras f, cameras t, roads r
WHERE f.camera_code='CAM-04' AND t.camera_code='CAM-03' AND r.road_code='DWK-CORR-1';
INSERT INTO camera_links (from_camera_id, to_camera_id, road_id, direction_label, path, distance_meters, free_flow_time_seconds, speed_limit_kph)
SELECT f.camera_id, t.camera_id, r.road_id, 'FWD',
       ST_SetSRID(ST_GeomFromGeoJSON('{"coordinates": [[77.067438, 28.596376], [77.067438, 28.596376], [77.067399, 28.596391], [77.067362, 28.596348], [77.06728, 28.596252], [77.066256, 28.595032], [77.06596, 28.594705], [77.06545, 28.594087], [77.065132, 28.5937], [77.06508, 28.593638], [77.065471, 28.593373], [77.065676, 28.593235], [77.065757, 28.593179], [77.065981, 28.593028], [77.066262, 28.592841], [77.06667, 28.59257], [77.066806, 28.592476], [77.067161, 28.592229], [77.067236, 28.592185], [77.068389, 28.59149], [77.069191, 28.590938], [77.069235, 28.590912], [77.069297, 28.590874], [77.069405, 28.590799], [77.069337, 28.590715], [77.069232, 28.590778]], "type": "LineString"}'), 4326), 936, 121, 50
FROM cameras f, cameras t, roads r
WHERE f.camera_code='CAM-04' AND t.camera_code='CAM-05' AND r.road_code='DWK-CORR-1';
INSERT INTO camera_links (from_camera_id, to_camera_id, road_id, direction_label, path, distance_meters, free_flow_time_seconds, speed_limit_kph)
SELECT f.camera_id, t.camera_id, r.road_id, 'REV',
       ST_SetSRID(ST_GeomFromGeoJSON('{"coordinates": [[77.069232, 28.590778], [77.069297, 28.590874], [77.070135, 28.59187], [77.070473, 28.592271], [77.071147, 28.593335], [77.07137, 28.593793], [77.071561, 28.594262], [77.071669, 28.594538], [77.071697, 28.594659], [77.071697, 28.59466], [77.071726, 28.594813], [77.071499, 28.594907], [77.071285, 28.594994], [77.069373, 28.595675], [77.069302, 28.595701], [77.069272, 28.595711], [77.067984, 28.59617], [77.067438, 28.596376]], "type": "LineString"}'), 4326), 968, 71, 50
FROM cameras f, cameras t, roads r
WHERE f.camera_code='CAM-05' AND t.camera_code='CAM-04' AND r.road_code='DWK-CORR-1';
INSERT INTO camera_links (from_camera_id, to_camera_id, road_id, direction_label, path, distance_meters, free_flow_time_seconds, speed_limit_kph)
SELECT f.camera_id, t.camera_id, r.road_id, 'FWD',
       ST_SetSRID(ST_GeomFromGeoJSON('{"coordinates": [[77.069232, 28.590778], [77.069297, 28.590874], [77.069405, 28.590799], [77.069337, 28.590715], [77.069135, 28.590473], [77.06748, 28.588478], [77.067377, 28.588356], [77.067356, 28.588332], [77.066651, 28.587534], [77.066046, 28.586849], [77.065566, 28.586306], [77.065482, 28.586211], [77.065249, 28.58594], [77.065165, 28.585842], [77.064214, 28.584716], [77.063773, 28.584209], [77.061889, 28.581999], [77.061836, 28.581937], [77.061717, 28.581797], [77.06165, 28.581717], [77.061545, 28.581789], [77.061611, 28.581867], [77.061669, 28.581829]], "type": "LineString"}'), 4326), 1317, 100, 50
FROM cameras f, cameras t, roads r
WHERE f.camera_code='CAM-05' AND t.camera_code='CAM-06' AND r.road_code='DWK-CORR-1';
INSERT INTO camera_links (from_camera_id, to_camera_id, road_id, direction_label, path, distance_meters, free_flow_time_seconds, speed_limit_kph)
SELECT f.camera_id, t.camera_id, r.road_id, 'REV',
       ST_SetSRID(ST_GeomFromGeoJSON('{"coordinates": [[77.061669, 28.581829], [77.061717, 28.581797], [77.06165, 28.581717], [77.061545, 28.581789], [77.061611, 28.581867], [77.063781, 28.584399], [77.064387, 28.585107], [77.064402, 28.585125], [77.064966, 28.585804], [77.065378, 28.586285], [77.065457, 28.586374], [77.065934, 28.586937], [77.066799, 28.587944], [77.06735, 28.588584], [77.069232, 28.590778]], "type": "LineString"}'), 4326), 1278, 90, 50
FROM cameras f, cameras t, roads r
WHERE f.camera_code='CAM-06' AND t.camera_code='CAM-05' AND r.road_code='DWK-CORR-1';
INSERT INTO camera_links (from_camera_id, to_camera_id, road_id, direction_label, path, distance_meters, free_flow_time_seconds, speed_limit_kph)
SELECT f.camera_id, t.camera_id, r.road_id, 'FWD',
       ST_SetSRID(ST_GeomFromGeoJSON('{"coordinates": [[77.061669, 28.581829], [77.061717, 28.581797], [77.061846, 28.581711], [77.063297, 28.580744], [77.06406, 28.580236], [77.065162, 28.579499], [77.06611, 28.578865], [77.068165, 28.577491], [77.068269, 28.577422], [77.06929, 28.576739], [77.06943, 28.576645], [77.069534, 28.57658]], "type": "LineString"}'), 4326), 965, 89, 50
FROM cameras f, cameras t, roads r
WHERE f.camera_code='CAM-06' AND t.camera_code='CAM-07' AND r.road_code='DWK-CORR-1';
INSERT INTO camera_links (from_camera_id, to_camera_id, road_id, direction_label, path, distance_meters, free_flow_time_seconds, speed_limit_kph)
SELECT f.camera_id, t.camera_id, r.road_id, 'REV',
       ST_SetSRID(ST_GeomFromGeoJSON('{"coordinates": [[77.069534, 28.57658], [77.069461, 28.576505], [77.069366, 28.576571], [77.06923, 28.576662], [77.066432, 28.578536], [77.063998, 28.580166], [77.063692, 28.580368], [77.061823, 28.581603], [77.061786, 28.581628], [77.06165, 28.581717], [77.061545, 28.581789], [77.061611, 28.581867], [77.061669, 28.581829]], "type": "LineString"}'), 4326), 1000, 99, 50
FROM cameras f, cameras t, roads r
WHERE f.camera_code='CAM-07' AND t.camera_code='CAM-06' AND r.road_code='DWK-CORR-1';
INSERT INTO camera_links (from_camera_id, to_camera_id, road_id, direction_label, path, distance_meters, free_flow_time_seconds, speed_limit_kph)
SELECT f.camera_id, t.camera_id, r.road_id, 'FWD',
       ST_SetSRID(ST_GeomFromGeoJSON('{"coordinates": [[77.069534, 28.57658], [77.069461, 28.576505], [77.068662, 28.575567], [77.066354, 28.572854], [77.06625, 28.572733], [77.066019, 28.572462], [77.06595, 28.57238], [77.065851, 28.572256], [77.065579, 28.571938], [77.065856, 28.571769], [77.066059, 28.571614], [77.066205, 28.571479], [77.066315, 28.571377], [77.066619, 28.570359], [77.066782, 28.569708], [77.066871, 28.569009], [77.06686, 28.568548], [77.066772, 28.568409], [77.066488, 28.568074], [77.065958, 28.567436], [77.064465, 28.565686], [77.064323, 28.56552], [77.063762, 28.564859], [77.062586, 28.563464], [77.06257, 28.563445], [77.062483, 28.563349], [77.062421, 28.563279], [77.062341, 28.563176], [77.062657, 28.562941], [77.063181, 28.561882], [77.063213, 28.561803], [77.06333, 28.56184], [77.063307, 28.561899], [77.062772, 28.562989], [77.062711, 28.563089], [77.062502, 28.563226], [77.062501, 28.563226]], "type": "LineString"}'), 4326), 2167, 174, 50
FROM cameras f, cameras t, roads r
WHERE f.camera_code='CAM-07' AND t.camera_code='CAM-08' AND r.road_code='DWK-CORR-1';
INSERT INTO camera_links (from_camera_id, to_camera_id, road_id, direction_label, path, distance_meters, free_flow_time_seconds, speed_limit_kph)
SELECT f.camera_id, t.camera_id, r.road_id, 'REV',
       ST_SetSRID(ST_GeomFromGeoJSON('{"coordinates": [[77.062501, 28.563226], [77.062421, 28.563279], [77.062332, 28.563334], [77.062396, 28.563408], [77.062497, 28.563527], [77.063675, 28.564918], [77.064381, 28.565745], [77.065128, 28.566625], [77.066318, 28.568026], [77.066402, 28.568126], [77.066698, 28.568474], [77.06676, 28.568642], [77.066764, 28.569009], [77.066653, 28.56969], [77.066512, 28.570277], [77.066495, 28.570362], [77.066302, 28.571021], [77.066246, 28.571152], [77.066156, 28.57128], [77.065948, 28.571513], [77.065879, 28.57159], [77.065651, 28.571772], [77.06551, 28.571858], [77.065384, 28.571935], [77.065453, 28.572015], [77.065737, 28.572349], [77.065792, 28.572413], [77.065879, 28.572527], [77.066202, 28.572901], [77.066215, 28.572916], [77.067784, 28.574734], [77.069366, 28.576571], [77.06943, 28.576645], [77.069534, 28.57658]], "type": "LineString"}'), 4326), 1826, 130, 50
FROM cameras f, cameras t, roads r
WHERE f.camera_code='CAM-08' AND t.camera_code='CAM-07' AND r.road_code='DWK-CORR-1';

INSERT INTO plates (normalized_plate) VALUES ('DL3CAB1234'), ('DL1CAA0007'), ('DL8CAF5678');

INSERT INTO sightings (source_event_id, camera_id, plate_id, raw_plate_text, normalized_plate_candidate, detection_confidence, ocr_confidence, ocr_candidates, validation_status, spotted_at, direction_degrees, vehicle_type, vehicle_color, lane_number, model_version)
VALUES
  ('seed-DL3CAB1234-CAM-01', (SELECT camera_id FROM cameras WHERE camera_code='CAM-01'), (SELECT plate_id FROM plates WHERE normalized_plate='DL3CAB1234'), 'DL3CAB1234', 'DL3CAB1234', 0.96, 0.93, '[]'::jsonb, 'accepted', now() - make_interval(secs => 1111), 180, 'car', 'white', 2, 'anpr-v1'),
  ('seed-DL3CAB1234-CAM-02', (SELECT camera_id FROM cameras WHERE camera_code='CAM-02'), (SELECT plate_id FROM plates WHERE normalized_plate='DL3CAB1234'), 'DL3CAB1234', 'DL3CAB1234', 0.96, 0.93, '[]'::jsonb, 'accepted', now() - make_interval(secs => 929), 180, 'car', 'white', 2, 'anpr-v1'),
  ('seed-DL3CAB1234-CAM-03', (SELECT camera_id FROM cameras WHERE camera_code='CAM-03'), (SELECT plate_id FROM plates WHERE normalized_plate='DL3CAB1234'), 'DL3CAB1234', 'DL3CAB1234', 0.96, 0.93, '[]'::jsonb, 'accepted', now() - make_interval(secs => 891), 180, 'car', 'white', 2, 'anpr-v1'),
  ('seed-DL3CAB1234-CAM-04', (SELECT camera_id FROM cameras WHERE camera_code='CAM-04'), (SELECT plate_id FROM plates WHERE normalized_plate='DL3CAB1234'), 'DL3CAB1234', 'DL3CAB1234', 0.96, 0.93, '[]'::jsonb, 'accepted', now() - make_interval(secs => 556), 180, 'car', 'white', 2, 'anpr-v1'),
  ('seed-DL3CAB1234-CAM-05', (SELECT camera_id FROM cameras WHERE camera_code='CAM-05'), (SELECT plate_id FROM plates WHERE normalized_plate='DL3CAB1234'), 'DL3CAB1234', 'DL3CAB1234', 0.96, 0.93, '[]'::jsonb, 'accepted', now() - make_interval(secs => 417), 180, 'car', 'white', 2, 'anpr-v1'),
  ('seed-DL3CAB1234-CAM-06', (SELECT camera_id FROM cameras WHERE camera_code='CAM-06'), (SELECT plate_id FROM plates WHERE normalized_plate='DL3CAB1234'), 'DL3CAB1234', 'DL3CAB1234', 0.96, 0.93, '[]'::jsonb, 'accepted', now() - make_interval(secs => 302), 180, 'car', 'white', 2, 'anpr-v1'),
  ('seed-DL3CAB1234-CAM-07', (SELECT camera_id FROM cameras WHERE camera_code='CAM-07'), (SELECT plate_id FROM plates WHERE normalized_plate='DL3CAB1234'), 'DL3CAB1234', 'DL3CAB1234', 0.96, 0.93, '[]'::jsonb, 'accepted', now() - make_interval(secs => 200), 180, 'car', 'white', 2, 'anpr-v1'),
  ('seed-DL3CAB1234-CAM-08', (SELECT camera_id FROM cameras WHERE camera_code='CAM-08'), (SELECT plate_id FROM plates WHERE normalized_plate='DL3CAB1234'), 'DL3CAB1234', 'DL3CAB1234', 0.96, 0.93, '[]'::jsonb, 'accepted', now() - make_interval(secs => 0), 180, 'car', 'white', 2, 'anpr-v1');

INSERT INTO sightings (source_event_id, camera_id, plate_id, raw_plate_text, normalized_plate_candidate, detection_confidence, ocr_confidence, ocr_candidates, validation_status, spotted_at, direction_degrees, vehicle_type, vehicle_color, lane_number, model_version)
VALUES
  ('seed-DL8CAF5678-CAM-01', (SELECT camera_id FROM cameras WHERE camera_code='CAM-01'), (SELECT plate_id FROM plates WHERE normalized_plate='DL8CAF5678'), 'DL8CAF5678', 'DL8CAF5678', 0.93, 0.88, '[]'::jsonb, 'accepted', now() - make_interval(secs => 600), 180, 'car', 'black', 3, 'anpr-v1'),
  ('seed-DL8CAF5678-CAM-08', (SELECT camera_id FROM cameras WHERE camera_code='CAM-08'), (SELECT plate_id FROM plates WHERE normalized_plate='DL8CAF5678'), 'DL8CAF5678', 'DL8CAF5678', 0.93, 0.88, '[]'::jsonb, 'accepted', now() - make_interval(secs => 595), 180, 'car', 'black', 3, 'anpr-v1');

INSERT INTO blacklist_entries (plate_id, reason, severity, status, added_by, case_reference)
SELECT plate_id, 'Reported stolen (demo)', 'high', 'active', 'seed', 'DWK-CASE-001' FROM plates WHERE normalized_plate='DL8CAF5678';

INSERT INTO alerts (dedup_key, alert_type, sighting_id, blacklist_entry_id, status, match_confidence, details)
SELECT 'seed-bl-DL8CAF5678', 'blacklist', s.sighting_id, b.blacklist_entry_id, 'new', 1.0,
       jsonb_build_object('note','blacklisted vehicle seen','camera','CAM-01')
FROM sightings s JOIN plates p ON p.plate_id=s.plate_id AND p.normalized_plate='DL8CAF5678'
JOIN blacklist_entries b ON b.plate_id=p.plate_id
WHERE s.source_event_id='seed-DL8CAF5678-CAM-01';

INSERT INTO alerts (dedup_key, alert_type, sighting_id, previous_sighting_id, anomaly_reason, status, match_confidence, details)
SELECT 'seed-anom-DL8CAF5678', 'route_anomaly', cur.sighting_id, prev.sighting_id, 'impossible_travel_time', 'new', 0.98, jsonb_build_object('observed_seconds',5)
FROM sightings cur JOIN sightings prev ON prev.source_event_id='seed-DL8CAF5678-CAM-01'
WHERE cur.source_event_id='seed-DL8CAF5678-CAM-08';

COMMIT;
